version: v1alpha1
debug: false
persist: false
machine:
  type: worker
  token: ""
  ca:
    crt: ""
    key: ""
  certSANs: []
  kubelet:
    image: ghcr.io/cozystack/cozystack/kubelet:v1.31.4
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
  network: {}
  install:
    disk: /dev/nvme0n1
    image: ghcr.io/urmanac/cozystack-assets/talos/cozystack-spin-tailscale/talos:latest
    wipe: false
  features:
    rbac: true
    stableHostname: true
    apidCheckExtKeyUsage: true
    diskQuotaSupport: true
    kubePrism:
      enabled: true
      port: 7445
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false
      resolveMemberNames: true
cluster:
  id: ""
  secret: ""
  controlPlane:
    endpoint: https://10.10.1.200:6443
  clusterName: cozystack-arm64
  network:
    dnsDomain: cluster.local
    podSubnets:
      - 10.244.0.0/16
    serviceSubnets:
      - 10.96.0.0/12
  token: ""
  ca:
    crt: ""
    key: ""
  discovery:
    enabled: false
    registries: {}
